export const OPEN_GITHUB_LOGIN = 'OPEN_LOGIN_PAGE';
export const AUTH_LOGIN_REQUEST_SUCCESS = 'AUTH_LOGIN_REQUEST_SUCCESS';
export const AUTH_LOGIN_REQUEST_ERROR = 'AUTH_LOGIN_REQUEST_ERROR';
export const LOGOUT = 'LOGOUT';
