export const OPEN_LOGIN_PAGE = 'OPEN_LOGIN_PAGE';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_REQUEST_SUCCESS = 'AUTH_LOGIN_REQUEST_SUCCESS';
export const AUTH_LOGIN_REQUEST_ERROR = 'AUTH_LOGIN_REQUEST_ERROR';
export const LOGOUT = 'LOGOUT';
